-- Student Application Tracker
-- Schema Definition (DDL)
-- Oracle SQL

-- ============================
-- ORGANIZATION
-- ============================
CREATE TABLE Organization (
    OrganizationID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Name CHAR(30) NOT NULL,
    CONSTRAINT pk_Organization PRIMARY KEY (OrganizationID)
);

-- ============================
-- STUDENT
-- ============================
CREATE TABLE Student (
    StudentID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Name CHAR(50) NOT NULL,
    Email VARCHAR2(50) UNIQUE NOT NULL,
    PhoneNumber VARCHAR2(12) UNIQUE NOT NULL,
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastLogin TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_Student PRIMARY KEY (StudentID)
);

-- ============================
-- ADMINISTRATOR
-- ============================
CREATE TABLE Administrator (
    AdminID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Name CHAR(50) NOT NULL,
    Email VARCHAR2(50) UNIQUE NOT NULL,
    PhoneNumber VARCHAR2(12) NOT NULL,
    Role CHAR(30) NOT NULL,
    OrganizationID NUMBER,
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastLogin TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_Administrator PRIMARY KEY (AdminID),
    CONSTRAINT fk_Admin_Org FOREIGN KEY (OrganizationID)
        REFERENCES Organization(OrganizationID)
);

-- ============================
-- ACADEMIC
-- ============================
CREATE TABLE Academic (
    StudentID NUMBER,
    Major CHAR(30) NOT NULL,
    School CHAR(30) NOT NULL,
    GraduationYear NUMBER,
    GPA DECIMAL(3,2),
    CONSTRAINT pk_Academic PRIMARY KEY (StudentID),
    CONSTRAINT fk_Academic_Student FOREIGN KEY (StudentID)
        REFERENCES Student(StudentID)
);

-- ============================
-- AUTHENTICATION
-- ============================
CREATE TABLE Student_Authentication (
    StudentID NUMBER,
    PasswordHash VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_StudentAuth PRIMARY KEY (StudentID),
    CONSTRAINT fk_StudentAuth FOREIGN KEY (StudentID)
        REFERENCES Student(StudentID)
);

CREATE TABLE Admin_Authentication (
    AdminID NUMBER,
    PasswordHash VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_AdminAuth PRIMARY KEY (AdminID),
    CONSTRAINT fk_AdminAuth FOREIGN KEY (AdminID)
        REFERENCES Administrator(AdminID)
);

-- ============================
-- POSTING
-- ============================
CREATE TABLE Posting (
    PostingID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Title CHAR(30) NOT NULL,
    Description VARCHAR2(500) NOT NULL,
    OrganizationID NUMBER NOT NULL,
    Deadline DATE NOT NULL,
    Type CHAR(15) NOT NULL,
    Hours CHAR(15) NOT NULL,
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_Posting PRIMARY KEY (PostingID),
    CONSTRAINT fk_Posting_Org FOREIGN KEY (OrganizationID)
        REFERENCES Organization(OrganizationID),
    CONSTRAINT chk_Posting_Type CHECK (Type IN ('Internship', 'Job', 'Scholarship')),
    CONSTRAINT chk_Posting_Hours CHECK (Hours IN ('Full time', 'Part time', 'Temporary'))
);

-- ============================
-- ADMINISTRATOR_POSTING (M:M)
-- ============================
CREATE TABLE Administrator_Posting (
    AdminID NUMBER,
    PostingID NUMBER,
    CONSTRAINT pk_Admin_Posting PRIMARY KEY (AdminID, PostingID),
    CONSTRAINT fk_AP_Admin FOREIGN KEY (AdminID)
        REFERENCES Administrator(AdminID),
    CONSTRAINT fk_AP_Posting FOREIGN KEY (PostingID)
        REFERENCES Posting(PostingID)
);

-- ============================
-- APPLICATION
-- ============================
CREATE TABLE Application (
    ApplicationID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    StudentID NUMBER NOT NULL,
    PostingID NUMBER NOT NULL,
    Status CHAR(15) NOT NULL,
    CONSTRAINT pk_Application PRIMARY KEY (ApplicationID),
    CONSTRAINT fk_App_Student FOREIGN KEY (StudentID)
        REFERENCES Student(StudentID),
    CONSTRAINT fk_App_Posting FOREIGN KEY (PostingID)
        REFERENCES Posting(PostingID),
    CONSTRAINT chk_App_Status CHECK (Status IN ('Pending', 'Accepted', 'Rejected'))
);

-- ============================
-- DOCUMENT
-- ============================
CREATE TABLE Document (
    DocumentID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    StudentID NUMBER NOT NULL,
    ApplicationID NUMBER NOT NULL,
    Type CHAR(15) NOT NULL,
    UploadedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_Document PRIMARY KEY (DocumentID),
    CONSTRAINT fk_Doc_Student FOREIGN KEY (StudentID)
        REFERENCES Student(StudentID),
    CONSTRAINT fk_Doc_App FOREIGN KEY (ApplicationID)
        REFERENCES Application(ApplicationID),
    CONSTRAINT chk_Doc_Type CHECK (Type IN ('Resume', 'Cover Letter', 'Transcript'))
);

-- ============================
-- APPLICATION_DOCUMENT (M:M)
-- ============================
CREATE TABLE Application_Document (
    ApplicationID NUMBER,
    DocumentID NUMBER,
    CONSTRAINT pk_App_Doc PRIMARY KEY (ApplicationID, DocumentID),
    CONSTRAINT fk_AppDoc_App FOREIGN KEY (ApplicationID)
        REFERENCES Application(ApplicationID),
    CONSTRAINT fk_AppDoc_Doc FOREIGN KEY (DocumentID)
        REFERENCES Document(DocumentID)
);

-- ============================
-- REMINDER
-- ============================
CREATE TABLE Reminder (
    ReminderID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    StudentID NUMBER NOT NULL,
    ApplicationID NUMBER NOT NULL,
    Deadline DATE NOT NULL,
    Message VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_Reminder PRIMARY KEY (ReminderID),
    CONSTRAINT fk_Rem_Student FOREIGN KEY (StudentID)
        REFERENCES Student(StudentID),
    CONSTRAINT fk_Rem_App FOREIGN KEY (ApplicationID)
        REFERENCES Application(ApplicationID)
);
